// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace FornavnEfternavn.WpfControls.Web.Server
{
    public partial class Movie
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime? ReleaseDate { get; set; }
        public string Director { get; set; }
        public bool IsColor { get; set; }
        public string Format { get; set; }
        public string Genre { get; set; }
    }
}