// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FornavnEfternavn.WpfControls.Web.Server.Models;
using Microsoft.EntityFrameworkCore;

namespace FornavnEfternavn.WpfControls.Web.Server.Data
{
    public partial class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext()
        {
        }

        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Movie> Movies { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
           
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Movie>(entity =>
            {
                entity.Property(e => e.Director).IsRequired();

                entity.Property(e => e.Format).IsRequired();

                entity.Property(e => e.Genre).IsRequired();

                entity.Property(e => e.Title).IsRequired();

                entity.Property(e => e.IsColor).IsRequired();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}